In [80]:
#mounnt your google dirve

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Exercise 7-9 Satatic

In [ ]:
# Import the Car_Prices data file and label it myData

import pandas as pd
myData1 = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/2510/2510-MH/Assignment/Ch7-Regression/Ch7_Q9_Data_File.xlsx', sheet_name = 'Car_Prices')
myData1.head(n=8)

   Price  Age  Mileage
0  13590    6    61485
1  13775    6    54344
2  22991    1     8246
3  15303    4    24856
4  16388    3    22100
5  16600    3    23702
6  16987    4    47401
7  18489    2    16888

In [ ]:
# Obtaining regression output

import statsmodels.formula.api as smf
Model = smf.ols('Price ~ Age + Mileage', data = myData1).fit()
print(Model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Price   R-squared:                       0.846
Model:                            OLS   Adj. R-squared:                  0.828
Method:                 Least Squares   F-statistic:                     46.83
Date:                Thu, 06 Nov 2025   Prob (F-statistic):           1.22e-07
Time:                        21:54:38   Log-Likelihood:                -172.69
No. Observations:                  20   AIC:                             351.4
Df Residuals:                      17   BIC:                             354.4
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   2.162e+04    784.664     27.552      0.000       2e+04    2.33e+04
Age        -1021.8213    186.807     -5.470      0.000   -1415.949    -627.693
Mileage       -0.0300      0.022     -1.352      0.194      -0.077       0.017
==============================================================================
Omnibus:                        1.578   Durbin-Watson:                   1.872
Prob(Omnibus):                  0.454   Jarque-Bera (JB):                1.151
Skew:                           0.347   Prob(JB):                        0.562
Kurtosis:                       2.052   Cond. No.                     1.21e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.21e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
# Obtaining prediction

# when Age = 7,  Mileage = 70000  --> must change for your homework assignment

print(Model.predict(pd.DataFrame({'Age': [7], 'Mileage': [70000]})))

0    12369.125995
dtype: float64

## Exercise 7-15

In [ ]:
# Import the Houses data file and label it myData
import pandas as pd
myData2 = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/2510/2510-MH/Assignment/Ch7-Regression/Ch7_Q15_V16_Data_File.xlsx', sheet_name = 'Houses')
myData2.head()

    Price  Sqft  Beds  Baths  Colonial
0  829000  2818     2    2.5         0
1  828000  2413     2    2.5         1
2  762000  2201     2    2.0         0
3  716000  2245     2    2.5         0
4  688000  2839     2    3.5         1

In [ ]:
# Obtaining regression output

import statsmodels.formula.api as smf

#Fill out the rest!

#Model = smf.ols('Price ~ Sqft+ Beds+ ...........', data = myData2).fit()

#print(Model.summary())

In [ ]:
 #Obtaining prediction interval for Time


 #alpha = 0.5 --> level of signifance

# Fill out the rest!

# print(Model.get_prediction( pd.DataFrame({'Sqft': [2500], 'Beds':[3], ..............})).summary_frame(alpha = .05))

## Exercise 7-17

In [81]:
# Import the Quarterbacks data file and label it myData

import pandas as pd
myData3 = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/2510/2510-MH/Assignment/Ch7-Regression/player2.xlsx')

myData3.head()

   Player    Salary    PC  TD  Age
0       1  25.55663  65.2  28   27
1       2  22.04409  60.5  27   26
2       3  20.50000  62.3  27   28
3       4  19.00468  66.1  26   38
4       5  17.00000  67.9  29   28

In [ ]:
# Obtaining regression output

import statsmodels.formula.api as smf

Model = smf.ols('Salary ~ PC+TD+Age', data = myData3).fit()

print(Model.summary())