In [20]:
# Mount theh google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [21]:
import pandas as pd

#Import the data file into a DataFrame (table) and label it myData

myData = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/2510/2510-MH/Assignment/Ch4/Ch4_Q7_V08_Data_File.xlsx')
myData

     Response    Quality
0           1       Fair
1           2       Good
2           3       Fair
3           4  Excellent
4           5       Good
..        ...        ...
145       146       Good
146       147       Fair
147       148  Excellent
148       149       Good
149       150       Good

[150 rows x 2 columns]

In [22]:


#Creating frequency distribution

Quality_Frequency = myData['Quality'].value_counts()

print(Quality_Frequency)

Quality
Good         71
Fair         32
Excellent    29
Poor         18
Name: count, dtype: int64

In [23]:
#Constructing bar chart

import seaborn as sns

#fill out the rest for your assignment

## Second problem

In [24]:
import pandas as pd

#Import the data file into a DataFrame (table) and label it myData2

myData2 = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/2510/2510-MH/Assignment/Ch4/Ch4_Q9_Data_File_V11.xlsx')
myData2

     Employee Personality     Sex
0           1    Diplomat  Female
1           2    Diplomat  Female
2           3    Explorer    Male
3           4    Diplomat  Female
4           5    Diplomat  Female
..        ...         ...     ...
995       996     Analyst  Female
996       997     Analyst  Female
997       998    Explorer  Female
998       999     Analyst  Female
999      1000    Diplomat    Male

[1000 rows x 3 columns]

In [25]:
#Creating frequency distribution

Sex_Frequency = myData2['Sex'].value_counts()

#Creating relative frequency distribution

Sex_Proportion = myData2['Sex'].value_counts(normalize = True)

#Combining distributions

combined_dist_sex = pd.DataFrame({

    'Frequency': Sex_Frequency,

    'Relative frequency': Sex_Proportion})

combined_dist_sex

        Frequency  Relative frequency
Sex
Male          509               0.509
Female        491               0.491

In [ ]:
#Creating frequency distribution for personality

#fill out the rest for your assignment

## Third Problem

In [26]:
import pandas as pd

#Import the data file into a DataFrame (table) and label it myData3

myData3 = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/2510/2510-MH/Assignment/Ch4/Ch4_Q21_Data_File.xlsx')
myData3

                   State  Price
0                 Alaska   3.06
1                Alabama   1.94
2               Arkansas   1.93
3                Arizona   2.66
4             California   3.35
5               Colorado   2.25
6            Connecticut   2.61
7   District of Columbia   2.58
8               Delaware   2.11
9                Florida   2.15
10               Georgia   2.08
11                Hawaii   3.37
12                  Iowa   1.98
13                 Idaho   2.56
14              Illinois   2.12
15               Indiana   2.03
16                Kansas   1.95
17              Kentucky   2.00
18             Louisiana   1.95
19         Massachusetts   2.53
20              Maryland   2.23
21                 Maine   2.30
22              Michigan   2.02
23             Minnesota   2.11
24              Missouri   1.84
25           Mississippi   1.94
26               Montana   2.41
27        North Carolina   2.14
28          North Dakota   2.24
29              Nebraska   2.05
30         New Hampshire   2.38
31            New Jersey   2.37
32            New Mexico   2.17
33                Nevada   2.94
34              New York   2.61
35                  Ohio   1.89
36              Oklahoma   1.91
37                Oregon   2.94
38          Pennsylvania   2.50
39          Rhode Island   2.47
40        South Carolina   1.94
41          South Dakota   2.18
42             Tennessee   2.00
43                 Texas   1.93
44                  Utah   2.59
45              Virginia   2.05
46               Vermont   2.54
47            Washington   3.09
48             Wisconsin   2.04
49         West Virginia   2.30
50               Wyoming   2.59

In [27]:
#Fill out the rest for your assignment


#Creating intervals

import numpy as np

#intervals = np.linspace(start = ?, stop = ?, num = ?)
#start should be 1.70 and stop should be 3.50. for num --> write down the six intervnals --> how many boundary numbers are used?

#Creating frequency distribution

# Frequency = pd.cut(myData3.Price .........)

#print(Frequency)

#Creating histogram

import seaborn as sns

#Constructing histogram